export interface Communication {
    id: string,
    creationDate: string,
    status: string,
    startDate: string,
    endDate: string,
    updateDate: string,
    idUser: string,
    idEstate: string,
    idCommunicationType: string,
    title: string,
    introduction: string,
    body: string,
    urlAttachmentDocument: string,
    signature: string,
}