export interface Visit {
  id: string,
  status: string,
  payment: string,
  startDate: string,
  endDate: string,
  idUser: string,
  idEstate: string,
  idSpace: string,
  idVisitType: string,
  idVehiculeType: string,
  visitorDocumentNumber: string,
  visitorName: string,
  description: string,
  licensePlate: string,
  value: number,
}